### ISSUE TITLE
Just white window

### ISSUE THREAD

**Issue by Eimis-dev** [omegaui/app_fleet#18]
When I open the app all I see is:

![image](https://github.com/omegaui/app_fleet/assets/10908092/cd6e43ef-e446-454c-ac9f-2e7df84eea18)

I installed it with `curl https://raw.githubusercontent.com/omegaui/app_fleet/main/network-install.sh | bash` with no errors.

I am on ubuntu 23.10, using mesa 23.3.4

Terminal output:

```
> ~ app-fleet                                                                               20:03:45

(app-fleet:535043): Gdk-CRITICAL **: 20:03:49.286: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed
flutter: Bad state: No element
flutter: #0      Iterable.first (dart:core/iterable.dart:643)
flutter: #1      LinuxAppFinder._parseDesktopEntry (package:app_fleet/config/assets/generators/linux_app_finder.dart:134)
flutter: #2      LinuxAppFinder._addAppsFrom (package:app_fleet/config/assets/generators/linux_app_finder.dart:123)
flutter: #3      LinuxAppFinder.initialize (package:app_fleet/config/assets/generators/linux_app_finder.dart:30)
flutter: #4      _AppFleetState.initState (package:app_fleet/main.dart:89)
flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5602)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5634)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5625)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #35     _RawViewElement._updateChild (package:flutter/src/widgets/view.dart:289)
flutter: #36     _RawViewElement.mount (package:flutter/src/widgets/view.dart:312)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5496)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:5187)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #42     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5447)
flutter: #43     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4326)
flutter: #44     Element.updateChild (package:flutter/src/widgets/framework.dart:3837)
flutter: #45     RootElement._rebuild (package:flutter/src/widgets/binding.dart:1334)
flutter: #46     RootElement.mount (package:flutter/src/widgets/binding.dart:1303)
flutter: #47     RootWidget.attach.<anonymous closure> (package:flutter/src/widgets/binding.dart:1256)
flutter: #48     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2835)
flutter: #49     RootWidget.attach (package:flutter/src/widgets/binding.dart:1255)
flutter: #50     WidgetsBinding.attachToBuildOwner (package:flutter/src/widgets/binding.dart:1083)
flutter: #51     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1065)
flutter: #52     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:1051)
flutter: #56     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:184)
flutter: (elided 3 frames from class _Timer and dart:async-patch)

```

**Comment by omegaui** [comment]
Hi! 
Thanks for reporting this issue,
its arising due to some desktop entry which is missing the common 'Name' key.
An update will arrive soon.

**Comment by omegaui** [comment]
@cybbro 
This issue is now fixed in the [**latest release**](https://github.com/omegaui/app_fleet/releases/tag/v1.0.0%2B10),
Let me know if its still happening for you.

**Comment by Eimis-dev** [comment]
> @cybbro This issue is now fixed in the [**latest release**](https://github.com/omegaui/app_fleet/releases/tag/v1.0.0%2B10), Let me know if its still happening for you.

I just tried, and as you said it is fixed indeed! Seems to work now, thank you!

![image](https://github.com/omegaui/app_fleet/assets/10908092/d5de5104-bfb6-4446-a4af-a26f1bb64739)
