### ISSUE TITLE
Window does not show up (assertion 'GDK_IS_WINDOW (window)' failed)

### ISSUE THREAD

**Issue by pesader** [omegaui/app_fleet#3]
Hi! I was trying to run App Fleet but I was unable to get it working. It launched a blank window as shown below:

[Screencast from 2023-10-10 20-39-33.webm](https://github.com/omegaui/app_fleet/assets/65264536/c3465702-730a-48ec-ae16-b6b64ab77688)

These were the logs printed to the terminal.

```log
Program name: ./app-fleet
Window size set to 750x600
flutter: PathNotFoundException: Directory listing failed, path = '/var/lib/snapd/desktop/applications/' (OS Error: No such file or directory, errno = 2)
flutter: #0      _Directory._fillWithDirectoryListing (dart:io-patch/directory_patch.dart:42)
flutter: #1      _Directory.listSync (dart:io/directory_impl.dart:233)
flutter: #2      LinuxAppFinder._addAppsFrom (package:app_fleet/config/assets/generators/linux_app_finder.dart:56)
flutter: #3      LinuxAppFinder.initialize (package:app_fleet/config/assets/generators/linux_app_finder.dart:28)
flutter: #4      _AppFleetState.initState (package:app_fleet/main.dart:85)
flutter: #5      StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5430)
flutter: #6      ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
flutter: #7      Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
flutter: #8      Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
flutter: #9      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
flutter: #10     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
flutter: #11     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
flutter: #12     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
flutter: #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
flutter: #16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:5462)
flutter: #17     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
flutter: #18     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
flutter: #19     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:5453)
flutter: #20     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
flutter: #21     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
flutter: #22     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
flutter: #23     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
flutter: #24     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
flutter: #25     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
flutter: #26     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
flutter: #27     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
flutter: #28     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
flutter: #29     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:5322)
flutter: #30     Element.rebuild (package:flutter/src/widgets/framework.dart:5016)
flutter: #31     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:5279)
flutter: #32     ComponentElement.mount (package:flutter/src/widgets/framework.dart:5273)
flutter: #33     Element.inflateWidget (package:flutter/src/widgets/framework.dart:4182)
flutter: #34     Element.updateChild (package:flutter/src/widgets/framework.dart:3707)
flutter: #35     RenderObjectToWidgetElement._rebuild (package:flutter/src/widgets/binding.dart:1253)
flutter: #36     RenderObjectToWidgetElement.mount (package:flutter/src/widgets/binding.dart:1222)
flutter: #37     RenderObjectToWidgetAdapter.attachToRenderTree.<anonymous closure> (package:flutter/src/widgets/binding.dart:1169)
flutter: #38     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2719)
flutter: #39     RenderObjectToWidgetAdapter.attachToRenderTree (package:flutter/src/widgets/binding.dart:1168)
flutter: #40     WidgetsBinding.attachRootWidget (package:flutter/src/widgets/binding.dart:1001)
flutter: #41     WidgetsBinding.scheduleAttachRootWidget.<anonymous closure> (package:flutter/src/widgets/binding.dart:981)
flutter: #45     _RawReceivePort._handleMessage (dart:isolate-patch/isolate_patch.dart:189)
flutter: (elided 3 frames from class _Timer and dart:async-patch)
```

There also seems to be an error due to the absence of the /var/lib/snapd/desktop/applications/ directory (which is my case, since I don't have snap intalled on this computer).

Thanks for developing App Fleet! 🚀

**Comment by omegaui** [comment]
I'll release a fix for this today as the v1.0.0+3 update.
Yes This is happening because of absence of snap.
The LinuxAppFinder module detects apps installed on the system, I guess adding a snap check would fix it.

Thank you for reporting this issue.

**Comment by omegaui** [comment]
Also, can you please try if the Launcher is coming up?
By running

```shell
app-fleet --mode launcher --debug
```

**Comment by omegaui** [comment]
@pesader 
The latest v1.0.0+3 has fixes for this issue.
Please try updating on your side.

**Comment by pesader** [comment]
Wow you were really quick! It's working, thank you.

![image](https://github.com/omegaui/app_fleet/assets/65264536/32db6d30-b566-4ea6-a96c-c87a0d8614f7)
